<?php

/**
 * @file
 * Main file for custom hooks and functions.
 */

use Drupal\imagemagick\ImagemagickExecArguments;

/**
 * Implements hook_theme().
 */
function dlog_theme($existing, $type, $theme, $path) {
  return [
    'dlog_previous_next' => [
      'variables' => [
        'entity' => NULL,
      ],
      'file' => 'dlog.theme.inc',
      'pattern' => 'dlog_previous_next__',
    ],
  ];
}

/**
 * Implements hook_imagemagick_arguments_alter().
 */
function dlog_imagemagick_arguments_alter(ImagemagickExecArguments $arguments, $command) {
  $arguments->add('-sampling-factor 4:2:0');
  $arguments->add('-interlace Plane');
  $arguments->add('-strip');
}
